CC = gcc
CFLAGS = -Wall -std=c11 -g -Iinclude

SRC = src/
BIN = bin/

EXEC = $(BIN)program
TEST = $(BIN)testMain

test :
	$(CC) $(CFLAGS) $(SRC)testMain.c -o $(TEST)

#all : list parser

#list :
#	static library liblist.a -> assign1/bin

#parser :
#	static library libparser.a -> assign1/bin

#clean :
#	rm $(BIN)*.o $(BIN)*.a
